### ISSUE TITLE
vim jupytext compatibility

### ISSUE THREAD

**Issue by qins** [GCBallesteros/dotfiles#1]
Hi,

Sorry about using this issue to discuss jupytext.vim's compatibility with newest jupytext.

Now jupytext can auto handle languages, and it's `--to` accept `auto`.

I saw your fork of jupytext.vim changed related code, could you have a look.

Now I'm using `md` format, but `auto` option can auto determine the corresponding language.

Thank you!

**Comment by GCBallesteros** [comment]
No worries @qins. I don't mind doing a small change to my fork but I'm not sure what you are asking for. Is it to add a flag to enable the new jupytext auto mode?

**Comment by qins** [comment]
That's correct. Add the auto mode.

I'm afraid the auto mode would be a tough one, because jupytext.vim can not get language type as before.

**Comment by GCBallesteros** [comment]
@qins It's been a long long time but you might be interested on [jupytext.nvim](https://github.com/GCBallesteros/jupytext.nvim). A lua port of jupytext.vim that I just released which will automatically do the language selection.
